name: ci-api

env:
  NODE_VERSION: 20
  WORKING_DIRECTORY: ./apps/api

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - .github/workflows/ci-api.yml
  pull_request:
    paths:
      - apps/api/**
      - .github/workflows/ci-api.yml

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npx turbo run lint --filter ${{ env.WORKING_DIRECTORY }}...

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npx turbo run test --filter ${{ env.WORKING_DIRECTORY }}...
      
      - name: Archive code coverage
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ${{ github.workflow }}-coverage
          path: ${{ env.WORKING_DIRECTORY }}/coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npx turbo run build --filter ${{ env.WORKING_DIRECTORY }}...

  sonarcloud:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.workflow }}-coverage
          path: ${{ env.WORKING_DIRECTORY }}/coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ env.WORKING_DIRECTORY }}
