name: sonar

env:
  NODE_VERSION: 20

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  sonarcloud-api:
    runs-on: ubuntu-latest
    name: SonarCloud Api

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npx turbo run test --filter=./apps/api
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
        with:
          projectBaseDir: apps/api
